### PR TITLE
chore: add `consult-emms--sort-album-function`

### PR DESCRIPTION
**Pull request by Elilif**
Enable customizing function for sorting tracks when retrieving a album.

### CODE REVIEW

**Comment by Hugo-Heagren** [comment]
Sorry for taking so long to take a proper look at this. It looks like a good idea. Could you also update the docstring for `consult-emms--get-album-tracks`, which currently mentions the old, hardcoded function, not the new option?

I'm not sure at the moment what the release status of this package will be (i.e. whether it will become part of EMMS, or be released separately, and if so where). I'd like to keep my options open, which means that all contributors need to assign copyright to the FSF. If you've already done this, that's great. If not, there are instructions on how to do so [here](https://www.fsf.org/licensing/assigning.html/?searchterm=copyright%20assignment).

**Comment by Elilif** [comment]
>  If the package is GNU then please email the maintainer of the program communicating your desire to assign copyright. The maintainer will then evaluate the appropriate type of assignment for your case.

Sorry for taking so long to take a proper look at this, too. So do I need email you to get a questionnaire or do something else ? I'm confused by the above message.

**Comment by Elilif** [comment]
I have signed the copyright assignment.

**Comment by Hugo-Heagren** [comment]
> I have signed the copyright assignment.

Great! The PR looks good to me, so I'll merge!

**Pull request merged**
